Setup spotless to enforce code-style
gurkenlabs/litiengine pull request #425
Opened 2021-10-14 08:36 UTC by weisJ

This PR sets up the gradle spotless plugin to automatically enforce code-style during builds. It's configured to use the google code style as specified here: https://github.com/gurkenlabs/litiengine/blob/master/CONTRIBUTING.md

~~Note that the github action to check code-style will currently fail and a commit fixing all style violations will have be necessary. I didn't include that commit as it would interfere with other PRs.~~

2021-12-04 21:35 UTC, weisJ commented
I have fixed some outstanding issues and everything should build fine now. The CI will now fail if files have malformed formatting. Most of the changes in this PR are just the result of running `gradlew spotlessApply` once after setting it up and are merely formatting related i.e. they don't change any actual content of files. If you want to see the relevant changes simply look at the changes for the first commit.

2021-12-28 14:29 UTC, nightm4re94 commented
Thanks for your PR!
Could you please resolve the merge conflicts here?

2021-12-28 14:56 UTC, weisJ commented
Done

2021-12-28 15:57 UTC, Gamebuster19901 requested changes
I went ahead and took a look at the first 50 files. Overall, I think the changes are good, but there are a few things I think these changes make worse. I recommend increasing the maximum line length before lines are split, as that's where it seems most of the issues are coming from.

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/Direction.java
> +   * o  0  o        LEFT = [225-315[
This comment seems broken now

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/GameRandom.java
> +            255);
I think this is harder to read than before.

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/abilities/AbilityExecution.java
> +            });
I think that braces should end on the same indent level that they open on.

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/CreatureMapObjectLoader.java
> +            new Object[] {customCreature});
I see no reason for the catch clause to be this long, having it on one line makes it more readable. Same with the log statement.

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/EmitterMapObjectLoader.java
> +            MapObjectProperty.Particle.TEXTS, EmitterData.DEFAULT_TEXT));
I believe that the maximum line length should be increased, this entire class was definitely much more readable before.

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/Environment.java
> +      // polyline or point MapObjects.
This comment has lines
that end after only
four or five words

2021-12-28 15:57 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/GameWorld.java
> +      new ConcurrentHashMap<>();
Same issues as before, increase max line length.

2021-12-28 16:13 UTC, Gamebuster19901 requested changes
Sorry about the duplicate review, I've remade it because before it only showed the 4 lines above the review comment.

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/Direction.java
> +   * o  0  o        LEFT = [225-315[
This comment seems broken now

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/GameRandom.java
> +            255);
I think this is harder to read than before.

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/abilities/AbilityExecution.java
> +            });
I think that braces should end on the same indent level that they open on.

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/CreatureMapObjectLoader.java
> +            new Object[] {customCreature});
I see no reason for the catch clause to be this long, having it on one line makes it more readable. Same with the log statement.

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/EmitterMapObjectLoader.java
> +            MapObjectProperty.Particle.TEXTS, EmitterData.DEFAULT_TEXT));
I believe that the maximum line length should be increased, this entire class was definitely much more readable before.

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/Environment.java
> +      // polyline or point MapObjects.
This comment has lines
that end after only
four or five words

2021-12-28 16:13 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/GameWorld.java
> +      new ConcurrentHashMap<>();
Same issues as before, we should increase max line length.

2021-12-28 16:16 UTC, weisJ commented
The formatting enforced strictly follows the Google Java style guide as per the contributing timelines: https://github.com/gurkenlabs/litiengine/blob/master/CONTRIBUTING.md

Some of the issues regarding line length I’ll be able to fix (especially everything related to comments), but others won’t be compliant with the Google style guide. If there are any hard opinions regarding some of the formatting a new style guide should be adopted (for example by using the Google style guide for the eclipse formatted as a basis and adjusting it accordingly).

2021-12-28 16:20 UTC, Gamebuster19901 commented
I think that a using modified style guide would probably be the best for this project, but obviously we should wait for @nightm4re94 and @steffen-wilke to get back with us.

2021-12-28 16:47 UTC, nightm4re94 commented
This is a discussion we have had very frequently recently. 
We are not pleased with the way Google Code Style enforces hard line wraps. Line breaks are often deliberate decisions that should not be messed with by automatic formatting. 
So no, we should not be using hard line breaks and therefore a modification to the code style convention is required.

2021-12-28 17:59 UTC, nightm4re94 commented
Since the google-java-format style is not configurable in terms of line length, I think we need to ditch this convention entirely.
It was chosen for being a renown and easy-to-distribute standard in the first place, but conventions shouldn't work against us 😄 
Before applying the google java code style, we've been using our own eclipse formatter:
```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<profiles version="12">
<profile kind="CodeFormatterProfile" name="gurkenlabs" version="12">
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_ellipsis" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_enum_declarations" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_in_empty_annotation_declaration" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_comma_in_allocation_expression" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_at_in_annotation_type_declaration" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.new_lines_at_block_boundaries" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_constructor_declaration_parameters" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_for_parameter" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_package" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_between_empty_parens_in_enum_constant" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.blank_lines_after_imports" value="1"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_paren_in_while" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_before_root_tags" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_between_empty_parens_in_annotation_type_member_declaration" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_comma_in_method_declaration_throws" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.format_javadoc_comments" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.indentation.size" value="2"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_postfix_operator" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_for_increments" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_type_arguments" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_comma_in_for_inits" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_in_empty_anonymous_type_declaration" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_semicolon_in_for" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.disabling_tag" value="@formatter:off"/>
<setting id="org.eclipse.jdt.core.formatter.continuation_indentation" value="2"/>
<setting id="org.eclipse.jdt.core.formatter.alignment_for_enum_constants" value="49"/>
<setting id="org.eclipse.jdt.core.formatter.blank_lines_before_imports" value="1"/>
<setting id="org.eclipse.jdt.core.formatter.blank_lines_after_package" value="1"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_binary_operator" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_multiple_local_declarations" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.alignment_for_arguments_in_enum_constant" value="16"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_angle_bracket_in_parameterized_type_reference" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.indent_root_tags" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.wrap_before_or_operator_multicatch" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.enabling_tag" value="@formatter:on"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_closing_brace_in_block" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_parenthesized_expression_in_return" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.alignment_for_throws_clause_in_method_declaration" value="16"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_parameter" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.keep_then_statement_on_same_line" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_field" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_explicitconstructorcall_arguments" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_in_empty_block" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_prefix_operator" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.blank_lines_between_type_declarations" value="1"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_brace_in_array_initializer" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_paren_in_for" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_paren_in_catch" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_angle_bracket_in_type_arguments" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_new_line_after_annotation_on_method" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_paren_in_switch" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_opening_brace_in_anonymous_type_declaration" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_closing_paren_in_parenthesized_expression" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.never_indent_line_comments_on_first_column" value="false"/>
<setting id="org.eclipse.jdt.core.compiler.problem.enumIdentifier" value="error"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_and_in_type_parameter" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_comma_in_for_inits" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.indent_statements_compare_to_block" value="true"/>
<setting id="org.eclipse.jdt.core.formatter.brace_position_for_anonymous_type_declaration" value="end_of_line"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_question_in_wildcard" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_opening_paren_in_annotation" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_comma_in_method_invocation_arguments" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_opening_brace_in_switch" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.comment.line_length" value="80"/>
<setting id="org.eclipse.jdt.core.formatter.use_on_off_tags" value="false"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_between_empty_brackets_in_array_allocation_expression" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_opening_brace_in_enum_constant" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_between_empty_parens_in_method_invocation" value="do not insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_assignment_operator" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_before_opening_brace_in_type_declaration" value="insert"/>
<setting id="org.eclipse.jdt.core.formatter.insert_space_after_opening_paren_in_for" value="do not inser [...]

2021-12-28 18:01 UTC, Gamebuster19901 commented
> Since the google-java-format style is not configurable in terms of line length, I think we need to ditch this convention entirely. It was chosen for being a renown and easy-to-distribute standard in the first place, but conventions shouldn't work against us smile Before applying the google java code style, we've been using our own eclipse formatter:

> It should be easy to apply an eclipse jdt format through spotless - what do you think of using this as a standard? How should we best distribute the configuration for others?

IIRC you need to modify .gitignore to include the settings file. Then anyone who uses eclipse will automatically have the settings file when they pull the repo.

2021-12-28 18:03 UTC, Gamebuster19901 commented
If you're using that as a global configuration, you will have to modify manually the project's configuration to use it so it will be included in the settings folder.

2021-12-28 18:39 UTC, nightm4re94 commented
What I don't like about this is that the engine is not meant to be an eclipse project specifically. The code formatter is, for example, applicable in IntelliJ as well. I'm not a fan of having IDE specific configs in the repo.

2021-12-28 18:47 UTC, weisJ commented
Spotless can be set up to read the eclipse formatting file (If you want customisation this is really the only option). Then formatting can be done by running `gradlew spotlessApply`. There is also an eclipse formatter plugin for IntelliJ.

2021-12-28 18:54 UTC, nightm4re94 commented
> Spotless can be set up to read the eclipse formatting file (If you want customisation this is really the only option). Then formatting can be done by running `gradlew spotlessApply`. There is also an eclipse formatter plugin for IntelliJ.

That's the variant I was suggesting, using a general purpose formatting file with the above settings.
I just don't want the file structure to be biased towards any IDE, if that makes sense.
Sorry by the way for withdrawing our approach using google format - at the time it seemed like a useful and quick way to encourage consistency in the repo.

2021-12-28 19:23 UTC, weisJ commented
> Sorry by the way for withdrawing our approach using google format - at the time it seemed like a useful and quick way to encourage consistency in the repo.

Don’t worry there really isn’t much overhead in setting up the formatting specifics of spotless.

FWIW I don’t think there is a large bias towards eclipse by including the file especially if it is stowed away in a `config` directory. However if needed we could also export the formatting config the IntelliJ format for `.editorconfig`. However I’m not sure whether this would result in equivalent formatting.

2021-12-28 22:52 UTC, weisJ commented
For reference I have commited what the code would look like with the eclipse config above.

2021-12-28 23:26 UTC, Gamebuster19901 reviewed
Definitely liking this so far.

Only thing that really seems off are how `case` statements are changed to not be indented.

Note: I've only reviewed some of the files in this pr.

2021-12-28 23:26 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/GameRandom.java
> +        0, 255);
I'd add a spotless off marker for this section, or increase the line limit by like 20 characters.

2021-12-28 23:26 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/EmitterMapObjectLoader.java
> +        mapObject.getFloatValue(MapObjectProperty.Particle.TTL_MAX)));
I actually think this change is better for readability.

2021-12-28 23:26 UTC, Gamebuster19901 commented on core/src/main/java/de/gurkenlabs/litiengine/environment/tilemap/MapUtilities.java
> +        maxTileBounds.getMaxY() - minTileBounds.getY());
The line breaks here are inconsistent. I think manual adjustment of the line break is probably best here.

2021-12-28 23:47 UTC, nightm4re94 commented
> Definitely liking this so far.
> 
> Only thing that really seems off are how `case` statements are changed to not be indented.
> 
> Note: I've only reviewed some of the files in this pr.

True, feel free to add an indentation for those.

2021-12-29 13:43 UTC, weisJ commented
Updated to include indentation for `case` labels. I also adjusted some settings to more closely match the existing formatting to reduce the amount of changes (mostly regarding brace location in empty/simple declarations).

2021-12-29 16:04 UTC, Gamebuster19901 approved these changes
LGTM, I have no problems if these changes get merged. Though I have left some notes on some of the changes, in case anyone else does.

2021-12-29 17:50 UTC, Gamebuster19901 commented
Looks like build failure is because spotlessapply wasn't applied properly

2021-12-29 18:18 UTC, weisJ commented
I properly rebased the branch and reapplied the formatting. Now with indented parameter descriptions in javadoc.

2021-12-29 19:17 UTC, Gamebuster19901 approved these changes

2021-12-29 20:13 UTC, merged

2022-01-07 00:40 UTC, Gamebuster19901 reviewed
CONTRIBUTING.md needs to be updated to reflect these changes.