Typo fixes
gurkenlabs/litiengine pull request #450
Opened 2022-01-25 00:40 UTC by mathieu-fanduel

2022-02-06 12:53 UTC, nightm4re94 commented
Hi, just checking in if this PR is still in draft state or ready for review?
cheers!

2022-02-07 08:52 UTC, mathieu-fanduel commented
Actually it could be reviewed , these are some hopefully minimal changes ( fixing typo ) to get my teeth in the code base and review process

2022-02-20 12:00 UTC, nightm4re94 commented
Hi, sorry this is taking longer than usual. We're on a sort of break from LITIENGINE due to heavy workload currently.
What I can say however is that we would prefer PullRequests that are separated into different topics, for example:
- one for fixing typos
- one for proposing Entity opacity
- one for Java 17 refactorings
This speeds up reviews and lets us merge parts even if other parts need revisions.

2022-02-20 18:13 UTC, mathieu-fanduel commented
Cool I will do that

2022-06-24 22:05 UTC, nightm4re94 commented
Hi there, just checking in whether you're still interested in splitting this PR up into three separate ones. That would facilitate the review greatly.

2022-06-26 17:57 UTC, nightm4re94 requested changes
Thanks a lot for this PR and please excuse me for taking a while with this review.
Two remarks:
* please remove all entity opacity related code
* please make sure to rebase the branch onto master and run the spotlessApply Gradle task to format everything according to our style guide.

Thanks again!

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/Game.java
> +   *          The arguments passed to the programs' entry point.
```suggestion
   *          The arguments passed to the program's entry point.
```

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/attributes/AttributeModifier.java
> + * An attribute modifier than allows modifying attributes by the specified Modification and modify value.
```suggestion
 * An attribute modifier that allows modifying attributes by the specified Modification and modify value.
```

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/entities/behavior/AStarPathFinder.java
> +import java.awt.*;
Please don't use wildcard imports.

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/entities/behavior/AStarPathFinder.java
> +    if ( targetNode == null ) {
You could combine the two `if`-conditions.

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/graphics/RenderEngine.java
> +import java.awt.*;
No wildcard imports, please.

2022-06-26 17:57 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/entities/Entity.java
> +  private float opacity = 1f;
While the idea of setting the drawing opacity is nice, I don't approve how it's implemented:
We should keep rendering-specific stuff separate from the Entity logic. 
The preferred way to achieve this visual effect would be to apply an ImageEffect in the Entity's AnimationController.

Please remove all Entity opacity related code from this PR.

2022-06-29 20:29 UTC, nightm4re94 commented on core/src/main/java/de/gurkenlabs/litiengine/entities/Entity.java
> +  private float opacity = 1f;
```suggestion
```

2022-12-15 21:12 UTC, nightm4re94 commented
Closing this due to inactivity. Thank you and feel free to resume at a later point :)

2022-12-15 21:12 UTC, closed without merging